---
- name: Install apache2
  apt:
    name: apache2
    state: present

- name: Start apache2 service
  service:
    name: apache2
    state: started
    enabled: true

- name: Create custom config
  template:
    src: 000-default.conf.j2
    dest: /etc/apache2/sites-available/000-default.conf
  notify: Restart apache