---
- name : Install docker and run flask container
  hosts: localhost

  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    

  tasks:
    - name: Install required packages
      apt:
        name: 
          - docker.io
          # Already installed as it is necessary for the ansible
          # pip package installed with the provision script
          - python3-pip
          - python3-docker
        state: present
        # Do apt-get update
        update_cache: true
      become: true

    - name: Copy the app to the VM
      copy:
        src: /vagrant/TP-Test-app
        dest: /home/vagrant
    
    - name: Copy the Dockerfile to the VM
      copy:
        src: /vagrant/dock-TP-Test_NP
        dest: /home/vagrant
    
    - name: Build docker image
      command: docker build -t tptest_24 -f /home/vagrant/dock-TP-Test_NP .
      args:
        chdir: /home/vagrant/
      become: true

    - name: Run docker container
      command: docker run --name run_tptest_24 -d -p 80:8082 tptest_24
      state: present
      become: true
