---
- name: Apt update
  hosts: all
  become: true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: true
        cache_valid_time: 3600  # Only update if cache is older than 1 hour

- name: Deploy web
  hosts: web
  become: true
  roles:
    - apache

- name: Deploy db
  hosts: db
  become: true
  roles:
    - mariadb