# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "server" do |server|
    server.vm.box = "ubuntu/focal64"
    server.vm.hostname = "dhcp-server"
    server.vm.network "private_network", ip: "192.168.1.1", virtualbox__intnet: "dhcp_net"
    server.vm.network "private_network", type: "dhcp"  # For SSH access
    server.vm.provision "ansible" do |ansible|
      ansible.playbook = "vm_dhcp.yml"
    end
  end
 
  config.vm.define "client" do |client|
    client.vm.box = "ubuntu/focal64"
    client.vm.hostname = "dhcp-client"
    client.vm.network "private_network", type: "dhcp", virtualbox__intnet: "dhcp_net"
    client.vm.network "private_network", type: "dhcp"  # For SSH access
  end
end
