---
- name: Install mariadb
  apt:
    name: mariadb-server
    state: present

- name: Start mariadb service
  service:
    name: mariadb
    state: started
    enabled: true

- name: Install python3-pymysql
  apt:
    name: python3-pymysql
    state: present

- name: Create database
  mysql_db:
    name: "{{ mariadb_db_name }}"
    state: present
    login_user: root
    login_password: ""
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Create user with remote access
  mysql_user:
    name: "{{ mariadb_user }}"
    password: "{{ mariadb_user_password }}"
    priv: "{{ mariadb_db_name }}.*:ALL"
    host: "%" # Allow access from any host
    state: present
    login_user: root
    login_password: ""
    login_unix_socket: /var/run/mysqld/mysqld.sock
    column_case_sensitive: false

- name: Update bind-address to listen on all interfaces
  lineinfile:
    path: /etc/mysql/mariadb.conf.d/50-server.cnf
    regexp: '^bind-address\s*='
    line: 'bind-address = 0.0.0.0'
    backup: yes
  notify: Restart mariadb