---
- name: Create a directory with specific ownership and permissions
  hosts: all
  become: yes
  vars:
    ansible_become_method: sudo
    ansible_become_flags: '-n'
  tasks:
    - name: Create a directory
      file:
        path: "/home/toto/test_directory"
        state: directory
        owner: toto
        group: toto
        mode: '0755'

    - name: Get directory information
      stat:
        path: "/home/toto/test_directory"
      register: dir_info

    - name: Display directory owner and permissions
      debug:
        msg: "The directory /home/toto/test_directory is owned by {{ dir_info.stat.pw_name }}:{{ dir_info.stat.gr_name }} with permissions {{ dir_info.stat.mode }}"